name: Build/release Electron app
on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build

      - name: Create Tag
        id: tag
        run: |
          TAG_NAME=v1.${{ github.run_number }}
          echo "::set-output name=TAG_NAME::$TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}      

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          draft: false
          files: |
            dist/*.snap            
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
